[internal]
checkpoints = 'Internal/Checkpoints'
raw = 'Internal/Raw/CSV'

[internal.reference]
reference = 'Internal/Reference'
scimago = 'Internal/Reference/Scimago'

[internal.manuscript]
figures = 'Figures'
tables = 'Tables'

[internal.intermediate]
csv = 'Internal/Intermediate/CSV'
graphs = 'Internal/Intermediate/Graphs'
models = 'Internal/Intermediate/Models'
embeddings = 'Internal/Intermediate/Embeddings'
classifier = 'Internal/Intermediate/Embeddings/Classifier'

[internal.intermediate.hdf5]
voyage = 'Internal/Intermediate/HDF5/VoyageAIEmbeddings'
neuro = 'Internal/Intermediate/HDF5/DomainEmbeddings'

[public]
csv = 'Public/CSV'
graphs = 'Public/Graphs'
models = 'Public/Models'

[public.embeddings]
voyage = 'Public/Embeddings/Voyage_Lite_02_Instruct'
neuro = 'Public/Embeddings/Custom_Neuro'
