[definition]
max_abstract_number = 200
required_fields = ['Keywords', 'Title', 'Description', 'Focus']

[distinction]
max_abstract_number = 200
required_fields = ['Distinguishing Features']

[questions]
required_fields = ['Open Questions']

[trends]
max_abstract_number = 200
older_cutoff = 2010
recent_cutoff = 2021
required_fields = [
                 'Emerging Themes',
                 'Emerging Methodological Approaches',
                 'Declining Themes',
                 'Declining Methodological Approaches'
                 ]

[dimensions]
max_abstract_number = 250
older_cutoff = 2010
recent_cutoff = 2021
required_fields = [
                'Dimension 1 - Appliedness', 'Dimension 2 - Psychological Domain',
                'Dimension 3 - Cognitive vs. Affective Focus',
                'Dimension 4 - Individual vs. Social Focus', 'Dimension 5 - Theory Engagement',
                'Dimension 6 - Theory Scope',
                'Dimension 7 - Methodological Approach',
                'Dimension 8 - Qualitative vs. Quantitative',
                'Dimension 9 - Interdisciplinarity'
        ]

[llm]
temperature = 1.0
model_name = 'gpt-4o-2024-08-06'
delay = 0.2
retries = 10
